---
# Source: ca-issuer/templates/1-vaultSecret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault-issuer-secret
  namespace: cert-manager
data:
  token: "cy5RYWlPVTZSYnJaMUJLbjVTNnpUYkhiZloK"
---
# Source: ca-issuer/templates/2-cert-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: vault-issuer
 namespace: cert-manager
spec:
  vault:
    path: "pki_int_vtc/sign/CommonCerts"
    server: "https://app01.vertechcon.lan:8200"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqekNDQW5lZ0F3SUJBZ0lVQlgxUVhidUw0V3F4ZWh6VFZkYU5KeWZSNWhRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRW1NQ1FHQTFVRUNoTWRWbVZ5YjI1dVpXRjFJRlJsWTJodWJ5NGdRMjl1YzJWcGJDQnBibU14UERBNgpCZ05WQkFNVE0xWmxjbTl1Ym1WaGRTQlVaV05vYm04dUlFTnZibk5sYVd3Z2FXNWpJRU5sY25ScFptbGpZWFJsCklFRjFkR2h2Y21sMGVUQWVGdzB5TVRBek1ETXhPREV6TWpOYUZ3MHpNVEF6TURFeE9ERXpOVE5hTURneE5qQTAKQmdOVkJBTVRMVlpsY205dWJtVmhkU0JVWldOb2JtOHVJRU52Ym5ObGFXd2dhVzVqTGlCSmJuUmxjbTFsWkdsaApkR1VnTVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0twQmM1OURheC9aazlBCnZSd2wzbU9mTmtReXlQdU5WL3Vkdm9LaUNoYU1ZS2xjbU95WC9HaEhVTEdGNDFhajlwN2gwQWRMUzJlcStSUWYKZDhpQ1BNUGhDM1ptQ2ZEamVlVkJMYlZKazlYbFQ1Q25EdzhTZWxES3N2bngrY3hER21RenhJbW5XY3plS2RhOApMRnErUkdNZktNRDdaWUZ3eTc2aGtVbHl1ajVsUDRweDNUWXJsSXVJUVlINGlqUFZiakprN2R3TmUrZmpKY3pYCmpyRVRKai9McFdkUEk2K0wzUjVOMGpMWU1KdlVOWE92VTVSSjhZYkloeVVLSFF1Y2RxWVBTc1RsWTFxSEliWWEKVWUvVHU2R2tFN3F3Qm9rSnU0YXhNSExNWkxpdGczRWRsdk9CemdsTU9sbk83cTFnKzY0K2tGbzRSNno1NGJPVQpzQ0d0NTBNQ0F3RUFBYU5qTUdFd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkhRWURWUjBPQkJZRUZBcVVlY3BYZ3NjM3dCeUtNai8vN3Axc3hwbzdNQjhHQTFVZEl3UVlNQmFBRk91SGxua3MKQmhoV1VpN245WUVYclppcE85S3FNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFMVUx4ZGFxR3M1VGdnMjN5bgpmelRpOG5rY0dBMzJHU1p3c0lZUXhnZmZMSHhiRlhZOHhKR1ZQK3ZaY0ErZEdvblY5U0V1VisyV3dEMUJoZDFKCktIVThjelJvL3BobnlNSkovY3ViR1F2S1hVa3pWT3BMUDdPeXQ1cUZQcjd0eGkyak1iMmxTK3RBS2M2Y0IzSEsKL1dLbGZTZ0wxOFRycmh4RCtWRFNlYWxWYzRYdlNtekNLdWRQSzFBYmNPY2RmWUJ6VC9oaHhsMVB0UUtkNFRnTgpubEtXaUVpVVZ6dHVCZTVnSFJkYUlvTE5VRXlEM2Vnd09LcVFiRmd6Y21VOHpNRmthSWRnd00zWWdaa2xTM0Y3CjJ4YTJ6YU53SGl5aUhjd0JvdE5Zd0FkWldDVktON1ovSkVqV0dtazQ2MVEvNEladG5NbmF4T1VWV0tRVE9La3MKZjY4VQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEdlRDQ0FxV2dBd0lCQWdJVVVWLzJlK2ZYY25MamkyMktkQXFKSkM2WVhjc3dEUVlKS29aSWh2Y05BUUVMCkJRQXdaakVtTUNRR0ExVUVDaE1kVm1WeWIyNXVaV0YxSUZSbFkyaHVieTRnUTI5dWMyVnBiQ0JwYm1NeFBEQTYKQmdOVkJBTVRNMVpsY205dWJtVmhkU0JVWldOb2JtOHVJRU52Ym5ObGFXd2dhVzVqSUVObGNuUnBabWxqWVhSbApJRUYxZEdodmNtbDBlVEFlRncweU1UQXpNRE14TmpNeE1qVmFGdzB6TVRBek1ERXhOak14TlRWYU1HWXhKakFrCkJnTlZCQW9USFZabGNtOXVibVZoZFNCVVpXTm9ibTh1SUVOdmJuTmxhV3dnYVc1ak1Ud3dPZ1lEVlFRREV6TlcKWlhKdmJtNWxZWFVnVkdWamFHNXZMaUJEYjI1elpXbHNJR2x1WXlCRFpYSjBhV1pwWTJGMFpTQkJkWFJvYjNKcApkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFYrbXJPVGpjYnBROUJydllaCm1DQlRQS0FNVEdLVk1DNlNjeEhDTk9LSDIzNERONW05OVlSUGxwNkdSRzVhUzBvS0NwTmMxajZOQzR1Y1QvUHIKZjQzUldnU21SRTNuL21ZMFprWU5lT1hhdVZPa05FSjBvSWVGTXRwb041amtYdFBuamM4ZXlQUStNTGZCZmxsbwpmRUViRytIRlk2K1l1cUdDamd0VGwwVUN6dnFHcllHTzJzd2I1R2w5Qkc4OE51WGFlNng2cS9URmdxV25HdzNaCkd3RXdsUVFPendFbWZQcDJXUHNGbGpMdHM2SEFNL1ZDWjd6WEMrSzI0cFZXdlF2VnBMdXl6d0lnMWlsaG8vUHoKK0xYVnNZaENnRWJOcFQ4SUZlaTlHc0UvRXFRRk9oN1RiRkhWZlVsdHdwN3Rsd3ZwRVJqWE9HWVVGQ08vUVFWdgpZYTIzQWdNQkFBR2pZekJoTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHCkExVWREZ1FXQkJUcmg1WjVMQVlZVmxJdTUvV0JGNjJZcVR2U3FqQWZCZ05WSFNNRUdEQVdnQlRyaDVaNUxBWVkKVmxJdTUvV0JGNjJZcVR2U3FqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSemVWRkEvSzZIRzhpbDQwU2dibgo0ZVlaYXlrSjdSVU9LazhnMC82TDRxMXFaNE5QN01TMzJZMzNRMzlBUjVxdDY2SzNqMTBFTXYybUFaalNLeDFvClU0VWtZSWJJajRKVFZvamFvY21yZ3NDYnlNYVJtSVl3bjN6YXdrVWRpYjlDdDlrd0hBb0xqSngvSFkwSlR2ZEIKc1RodzJuNWJmMi9Zc29VYWZjOTVMTTdXb1hYL3Z2V3FPYVNZZkw4YnJEVU1FZ1ZWMm9rdGFiWlNLY25JWTJTSQo2WWRZR0d4bG1zWXBzQmZxU3JzeDV4cUU2a1FXQWYyMTY5Y0s2TmlTSHM2ME44eWlLZjlCWnIxeURzN2IvWkRTClY4a0FzbFZuSzlQWFVqMTY0aHRtc2FJRDZsSDRndnFXNWx2ZExnYnF3S3ZxVStjejlrNFhPWmhIem01MGRsZmoKdXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    auth:
      tokenSecretRef:
        name: vault-issuer-secret
        key: token

---

apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job-name: refresh-token
  name: refresh-token
  namespace: cert-manager
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null

    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: Never
          containers:
            - name: "container-0"
              args:
                - /bin/sh
                - '-c'
                - >-
                  curl -k --header "X-Vault-Token: ${TOKEN}" --request POST
                  https://app01.vertechcon.lan:8200/v1/auth/token/renew-self
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: vault-issuer-secret
                      optional: false
              image: curlimages/curl
              imagePullPolicy: Always

  schedule: 0 1 1/1 * *
  suspend: false
#  startingDeadlineSeconds: int
#  timeZone: string