apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "registry.name" . }}
spec:
  {{- with .Values.ingress.tls }}
  tls:
  {{ toYaml . | nindent 2 }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
