apiVersion: v1
data:
  DB_BACKEND: {{ "POSTGRES" | b64enc }}
  HOST: {{ .Values.dbConfig.host | b64enc }}
  POSTGRES_PORT: {{ "5432" | b64enc }}
  POSTGRES_DB: {{ .Values.dbConfig.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.dbConfig.username | b64enc }}
  POSTGRES_PASS: {{ .Values.dbConfig.password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "geoserver.dbsecret" . }}