apiVersion: v1
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "metabase.dbsecret" . }}