apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "comax-web.awsSecretName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "comax-web.serviceAccountName" . }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc }}
  CONNSTR: {{ .Values.connstr | b64enc }}