apiVersion: v1
kind: Service
metadata:
  name: {{ include "comax-web.fullname" . }}
  labels:
    {{- include "comax-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.ip }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "comax-web.selectorLabels" . | nindent 4 }}
