{{- if .Values.keystores.pkcs12password -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "issuerCertificate.pkcsSecret" . }}
data:
  password-key: "{{ .Values.keystores.pkcs12password | b64enc }}"
{{- end -}}